name: Conventional Commits

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize
        paths:
            - "my_helper_package/src/ilsadvbisnvavojebaij/**"
            - ".github/workflows/conventional-commits.yml"

permissions:
    pull-requests: write

jobs:
    main:
        name: Validate PR title
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              id: lint_pr_title
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - uses: marocchino/sticky-pull-request-comment@v2
              # When the previous steps fails, the workflow would stop. By adding this
              # condition you can continue the execution with the populated error message.
              if: always() && (steps.lint_pr_title.outputs.error_message != null)
              with:
                  header: pr-title-lint-error
                  message: |
                      Hey there! 👋🏼

                      We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org).

                      It looks like your proposed title needs to be adjusted.

                      Details:

                      ```
                      ${{ steps.lint_pr_title.outputs.error_message }}
                      ```

            # Delete a previous comment when the issue has been resolved
            - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  header: pr-title-lint-error
                  delete: true
