name: "Python Release PR"

on:
    push:
        branches: [pysdk/v*]
    pull_request:
        branches: [pysdk/v*]

# concurrency:
#     group: test-python-${{ github.head_ref }}
#     cancel-in-progress: true

# TODOS:
#  - Fix scope of env variables
#  - Caching setup python
#  - Upload/download artifacts
#  - Should we cache artifacts?
#  - Caching dependencies
#  - Concurrency settings
#  - Permissions
env:
    python-version: "3.8.16"
    pip-version: 23.1.2
    package-dir: "./my_helper_package"
    build-version: 0.10.0
    check-wheel-contents-version: 0.4.0
    twine-version: 4.0.2
jobs:
    warning:
        name: "Warnning for release PR"
        runs-on: ubuntu-latest
        steps:
            - run: echo "Show a warning for this PR will create a release of our python package, once merged"
    lint:
        name: "Test Python Style"
        uses: ./.github/workflows/style-python.yml
    test:
        name: "Run Python tests"
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Running tests..."
    build:
        # FIX ME!!
        # needs: [lint, test]
        name: "Build Python package"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Set up python ${{ env.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip==${{ env.pip-version }}
                  pip install build==${{ env.build-version }} check-wheel-contents==${{ env.check-wheel-contents-version }} twine==${{ env.twine-version }}
            - name: Build
              run: |
                  cd "${{ env.package-dir }}"
                  python3 -m build
            - name: Check wheels
              run: |
                  cd "${{ env.package-dir }}"
                  python3 -m check_wheel_contents dist/
                  python3 -m twine check dist/*
    publish-package:
        needs: build
        # if: github.event_name == 'push' || github.event_path == 'workflow_dispatch'
        name: "Publish Python Package"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Set up python ${{ env.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip==${{ env.pip-version }}
                  pip install twine==${{ env.twine-version }}
            - name: "Tag commit"
              uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.git.createRef({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        ref: 'refs/tags/<tagname>',
                        sha: context.sha
                      })
            - name: "Publish Python package to Pypi"
              run: |
                  cd "${{ env.package-dir }}"
                  echo "Publishing to Pypi..."
                  python3 -m twine upload dist/* --verbose
            - name: "Sync to public repo"
              run: |
                  echo "Syncing to public repo..."
