name: "Python Release PR"

on:
    pull_request:
        branches: [pysdk/v*]

# concurrency:
#     group: test-python-${{ github.head_ref }}
#     cancel-in-progress: true

jobs:
    lint:
        name: "Test Python Style"
        uses: ./.github/workflows/style-python.yml
    test:
        name: "Run Python tests"
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Running tests..."
    build:
        needs: [lint, test]
        name: "Build Python package"
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Building package..."
    publish-to-pypi:
        needs: build
        name: "Publish Python package to Pypi"
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Publishing to Pypi..."
    publish-to-public-repo:
        needs: build
        name: "Sync to public repo"
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Syncing to public repo..."
