name: "Python Style"

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        # The branches below must be a subset of the branches above
        paths:
            - "my_helper_package/src/ilsadvbisnvavojebaij/**"
            - ".github/workflows/style-python.yml"
        branches-ignore:
            - main # This workflow is called as part of the python-release-pr workflow
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    workflow_call:

concurrency:
    group: test-python-${{ github.head_ref }}
    cancel-in-progress: true

env:
    python-version: 3.9
    pip-version: 21.2.2
    black-version: 22.3.0
    flake8-version: 5.0.4
    isort-version: 5.12.0
    line-length: 100

jobs:
    lint:
        name: "Check Linting"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Set up python ${{ env.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip==${{ env.pip-version }}
                  pip install black==${{ env.black-version }} flake8==${{ env.flake8-version }} isort==${{ env.isort-version }} colorama
            - name: Run fix style script & check diff
              run: |
                  ./scripts/fix_python_style.sh
                  git diff --exit-code
