name: "Test custom action from public repo"

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        name: "Test action"
        runs-on: ubuntu-latest
        run: |
            echo "Hello"
        # uses: fjcasti1/python-release-on-pr@main
